apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/kube-default: true
    app: jenkins
    component: agent
spec:
  containers:
  - name: terragrunt-azure
    image: icmesimage.azurecr.io/slaveimage:1.0.1
    pullsecretkey: ewoJImF1dGhzIjogewoJCSJpY21lc2ltYWdlLmF6dXJlY3IuaW8iOiB7CgkJCSJhdXRoIjogIllqVmtPR0V3T1RVdFlqZGxaUzAwTTJOakxXSTJOalF0TVdVd05USTRZVE5rTVRVNE9tcElTemRSZmxOUE9VaE5NV3cxUWt0cUxVRnpOSE14VjI1S1ExSkNSSFpXYkhGWk1HWT0iCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjUgKGxpbnV4KSIKCX0KfQ==
    command:
    - sleep
    args:
    - 99d
  nodeSelector:
    jenkins: worker
  tolerations:
  - key: jenkins
    operator: Equal
    value: worker
    effect: NoSchedule
